# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cit_doi', models.CharField(max_length=100)),
                ('create_ctime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_doi', models.CharField(max_length=100)),
                ('create_rtime', models.DateField()),
            ],
        ),
    ]
