# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_doi', models.CharField(max_length=100)),
                ('create_stime', models.DateField()),
            ],
        ),
    ]
