# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0002_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('star_doi', models.CharField(max_length=100)),
                ('star_time', models.DateField()),
            ],
        ),
    ]
