# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0003_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='star_title',
            field=models.CharField(default='Unknown', max_length=500),
            preserve_default=False,
        ),
    ]
