# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0007_pagination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('sea_type', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
                ('page_from', models.CharField(max_length=100)),
                ('page_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=3000)),
            ],
        ),
    ]
