# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0008_sea'),
    ]

    operations = [
        migrations.AddField(
            model_name='sea',
            name='keyword',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
