# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0009_sea_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='star_file',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
