# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualRef', '0013_auto_20180518_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='reference_count',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
